# Generated by Django 4.2.16 on 2025-10-16 23:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="valor_hora",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor cobrado por hora de trabalho",
                max_digits=10,
                verbose_name="Valor por Hora",
            ),
        ),
    ]
