# Generated by Django 4.2.16 on 2025-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_jira_id_user_valor_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='project_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='team_member',
            field=models.BooleanField(default=False),
        ),
    ]
