-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.accounts_user_groups_id_seq;

CREATE SEQUENCE public.accounts_user_groups_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.accounts_user_id_seq;

CREATE SEQUENCE public.accounts_user_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.accounts_user_user_permissions_id_seq;

CREATE SEQUENCE public.accounts_user_user_permissions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.auth_group_id_seq;

CREATE SEQUENCE public.auth_group_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.auth_group_permissions_id_seq;

CREATE SEQUENCE public.auth_group_permissions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.auth_permission_id_seq;

CREATE SEQUENCE public.auth_permission_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.core_dimissue_id_seq;

CREATE SEQUENCE public.core_dimissue_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.core_factesforco_id_seq;

CREATE SEQUENCE public.core_factesforco_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.dim_dev_id_seq;

CREATE SEQUENCE public.dim_dev_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.dim_intervalo_temporal_id_seq;

CREATE SEQUENCE public.dim_intervalo_temporal_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.dim_issue_type_id_seq;

CREATE SEQUENCE public.dim_issue_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.dim_projeto_id_seq;

CREATE SEQUENCE public.dim_projeto_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.dim_status_id_seq;

CREATE SEQUENCE public.dim_status_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.django_admin_log_id_seq;

CREATE SEQUENCE public.django_admin_log_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.django_content_type_id_seq;

CREATE SEQUENCE public.django_content_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.django_migrations_id_seq;

CREATE SEQUENCE public.django_migrations_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.fato_issue_id_seq;

CREATE SEQUENCE public.fato_issue_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.fato_projeto_snapshot_id_seq;

CREATE SEQUENCE public.fato_projeto_snapshot_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.issue_id_seq;

CREATE SEQUENCE public.issue_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.log_tempo_id_seq;

CREATE SEQUENCE public.log_tempo_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.projeto_id_seq;

CREATE SEQUENCE public.projeto_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.type_issue_id_seq;

CREATE SEQUENCE public.type_issue_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.type_status_id_seq;

CREATE SEQUENCE public.type_status_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.accounts_user definition

-- Drop table

-- DROP TABLE public.accounts_user;

CREATE TABLE public.accounts_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	email varchar(254) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	jira_id varchar(100) NULL,
	valor_hora numeric(10, 2) NOT NULL,
	project_admin bool NOT NULL,
	project_manager bool NOT NULL,
	team_leader bool NOT NULL,
	team_member bool NOT NULL,
	CONSTRAINT accounts_user_pkey PRIMARY KEY (id),
	CONSTRAINT accounts_user_username_key UNIQUE (username)
);
CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


-- public.auth_group definition

-- Drop table

-- DROP TABLE public.auth_group;

CREATE TABLE public.auth_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- public.dim_dev definition

-- Drop table

-- DROP TABLE public.dim_dev;

CREATE TABLE public.dim_dev (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	dev_name varchar(255) NOT NULL,
	id_dev_jiba int4 NOT NULL,
	id_dev_jira varchar(100) NOT NULL,
	valor_hora numeric(10, 2) NULL,
	CONSTRAINT dim_dev_pkey PRIMARY KEY (id)
);
CREATE INDEX dim_dev_id_dev_jiba_f3948717 ON public.dim_dev USING btree (id_dev_jiba);


-- public.dim_intervalo_temporal definition

-- Drop table

-- DROP TABLE public.dim_intervalo_temporal;

CREATE TABLE public.dim_intervalo_temporal (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	granularity_type varchar(50) NOT NULL,
	start_date timestamptz NULL,
	end_date timestamptz NULL,
	CONSTRAINT dim_intervalo_temporal_pkey PRIMARY KEY (id)
);


-- public.dim_issue_type definition

-- Drop table

-- DROP TABLE public.dim_issue_type;

CREATE TABLE public.dim_issue_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_type_jira int4 NOT NULL,
	id_type_jiba int4 NOT NULL,
	name_type varchar(100) NOT NULL,
	CONSTRAINT dim_issue_type_pkey PRIMARY KEY (id)
);


-- public.dim_projeto definition

-- Drop table

-- DROP TABLE public.dim_projeto;

CREATE TABLE public.dim_projeto (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_project_jiba int4 NOT NULL,
	id_project_jira int4 NOT NULL,
	project_name varchar(255) NOT NULL,
	start_date date NOT NULL,
	end_date date NULL,
	CONSTRAINT dim_projeto_id_project_jiba_key UNIQUE (id_project_jiba),
	CONSTRAINT dim_projeto_id_project_jira_key UNIQUE (id_project_jira),
	CONSTRAINT dim_projeto_pkey PRIMARY KEY (id)
);


-- public.dim_status definition

-- Drop table

-- DROP TABLE public.dim_status;

CREATE TABLE public.dim_status (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_status_jira int4 NOT NULL,
	id_status_jiba int4 NOT NULL,
	status_name varchar(100) NOT NULL,
	"key" varchar(100) NULL,
	CONSTRAINT dim_status_pkey PRIMARY KEY (id)
);
CREATE INDEX dim_status_id_status_jiba_71862394 ON public.dim_status USING btree (id_status_jiba);
CREATE INDEX dim_status_id_status_jira_989f9ad7 ON public.dim_status USING btree (id_status_jira);


-- public.django_content_type definition

-- Drop table

-- DROP TABLE public.django_content_type;

CREATE TABLE public.django_content_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);


-- public.django_migrations definition

-- Drop table

-- DROP TABLE public.django_migrations;

CREATE TABLE public.django_migrations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamptz NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);


-- public.django_session definition

-- Drop table

-- DROP TABLE public.django_session;

CREATE TABLE public.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


-- public.projeto definition

-- Drop table

-- DROP TABLE public.projeto;

CREATE TABLE public.projeto (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"key" varchar(50) NOT NULL,
	"name" varchar(255) NOT NULL,
	description text NOT NULL,
	start_date_project date NULL,
	end_date_project date NULL,
	"uuid" text NOT NULL,
	jira_id int4 NOT NULL,
	"projectTypeKey" varchar(100) NOT NULL,
	CONSTRAINT projeto_jira_id_key UNIQUE (jira_id),
	CONSTRAINT projeto_key_key UNIQUE (key),
	CONSTRAINT projeto_pkey PRIMARY KEY (id),
	CONSTRAINT projeto_uuid_key UNIQUE (uuid)
);
CREATE INDEX projeto_key_bb4a4898_like ON public.projeto USING btree (key varchar_pattern_ops);
CREATE INDEX projeto_uuid_257704d0_like ON public.projeto USING btree (uuid text_pattern_ops);


-- public.type_issue definition

-- Drop table

-- DROP TABLE public.type_issue;

CREATE TABLE public.type_issue (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	description text NOT NULL,
	subtask bool NOT NULL,
	jira_id int4 NOT NULL,
	CONSTRAINT type_issue_jira_id_key UNIQUE (jira_id),
	CONSTRAINT type_issue_pkey PRIMARY KEY (id)
);


-- public.type_status definition

-- Drop table

-- DROP TABLE public.type_status;

CREATE TABLE public.type_status (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"key" varchar(255) NOT NULL,
	"name" text NOT NULL,
	jira_id int4 NOT NULL,
	CONSTRAINT type_status_jira_id_key UNIQUE (jira_id),
	CONSTRAINT type_status_pkey PRIMARY KEY (id)
);


-- public.accounts_user_groups definition

-- Drop table

-- DROP TABLE public.accounts_user_groups;

CREATE TABLE public.accounts_user_groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id),
	CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);
CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


-- public.auth_permission definition

-- Drop table

-- DROP TABLE public.auth_permission;

CREATE TABLE public.auth_permission (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	content_type_id int4 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


-- public.core_dimissue definition

-- Drop table

-- DROP TABLE public.core_dimissue;

CREATE TABLE public.core_dimissue (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_issue_jiba int4 NOT NULL,
	id_issue_jira int4 NOT NULL,
	created_at timestamptz NOT NULL,
	start_date timestamptz NULL,
	issue_type_id int4 NOT NULL,
	project_id int4 NOT NULL,
	CONSTRAINT core_dimissue_pkey PRIMARY KEY (id),
	CONSTRAINT core_dimissue_issue_type_id_9c0c7680_fk_dim_issue_type_id FOREIGN KEY (issue_type_id) REFERENCES public.dim_issue_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT core_dimissue_project_id_728d06b2_fk_dim_projeto_id FOREIGN KEY (project_id) REFERENCES public.dim_projeto(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX core_dimissue_id_issue_jiba_70228c09 ON public.core_dimissue USING btree (id_issue_jiba);
CREATE INDEX core_dimissue_id_issue_jira_5ea63220 ON public.core_dimissue USING btree (id_issue_jira);
CREATE INDEX core_dimissue_issue_type_id_9c0c7680 ON public.core_dimissue USING btree (issue_type_id);
CREATE INDEX core_dimissue_project_id_728d06b2 ON public.core_dimissue USING btree (project_id);


-- public.core_factesforco definition

-- Drop table

-- DROP TABLE public.core_factesforco;

CREATE TABLE public.core_factesforco (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	accumulated_cost numeric(15, 2) NOT NULL,
	accumulated_minutes int4 NOT NULL,
	created_at timestamptz NOT NULL,
	dev_id int4 NOT NULL,
	project_id int4 NOT NULL,
	worklog_interval_id int4 NOT NULL,
	CONSTRAINT core_factesforco_pkey PRIMARY KEY (id),
	CONSTRAINT core_factesforco_dev_id_dae17261_fk_dim_dev_id FOREIGN KEY (dev_id) REFERENCES public.dim_dev(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT core_factesforco_project_id_ca879dc6_fk_dim_projeto_id FOREIGN KEY (project_id) REFERENCES public.dim_projeto(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT core_factesforco_worklog_interval_id_0c6172d8_fk_dim_inter FOREIGN KEY (worklog_interval_id) REFERENCES public.dim_intervalo_temporal(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX core_factesforco_dev_id_dae17261 ON public.core_factesforco USING btree (dev_id);
CREATE INDEX core_factesforco_project_id_ca879dc6 ON public.core_factesforco USING btree (project_id);
CREATE INDEX core_factesforco_worklog_interval_id_0c6172d8 ON public.core_factesforco USING btree (worklog_interval_id);


-- public.django_admin_log definition

-- Drop table

-- DROP TABLE public.django_admin_log;

CREATE TABLE public.django_admin_log (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	action_time timestamptz NOT NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	content_type_id int4 NULL,
	user_id int8 NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


-- public.fato_issue definition

-- Drop table

-- DROP TABLE public.fato_issue;

CREATE TABLE public.fato_issue (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	total_issue int4 NOT NULL,
	created_at timestamptz NOT NULL,
	issue_type_id int4 NOT NULL,
	project_id int4 NOT NULL,
	status_id int4 NOT NULL,
	worklog_interval_id int4 NOT NULL,
	CONSTRAINT fato_issue_pkey PRIMARY KEY (id),
	CONSTRAINT fato_issue_issue_type_id_86d1dc1c_fk_dim_issue_type_id FOREIGN KEY (issue_type_id) REFERENCES public.dim_issue_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT fato_issue_project_id_17032e67_fk_dim_projeto_id FOREIGN KEY (project_id) REFERENCES public.dim_projeto(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT fato_issue_status_id_a4ca8d20_fk_dim_status_id FOREIGN KEY (status_id) REFERENCES public.dim_status(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT fato_issue_worklog_interval_id_b294a34b_fk_dim_inter FOREIGN KEY (worklog_interval_id) REFERENCES public.dim_intervalo_temporal(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX fato_issue_issue_type_id_86d1dc1c ON public.fato_issue USING btree (issue_type_id);
CREATE INDEX fato_issue_project_b63d1f_idx ON public.fato_issue USING btree (project_id, worklog_interval_id);
CREATE INDEX fato_issue_project_id_17032e67 ON public.fato_issue USING btree (project_id);
CREATE INDEX fato_issue_status_id_a4ca8d20 ON public.fato_issue USING btree (status_id);
CREATE INDEX fato_issue_worklog_interval_id_b294a34b ON public.fato_issue USING btree (worklog_interval_id);


-- public.fato_projeto_snapshot definition

-- Drop table

-- DROP TABLE public.fato_projeto_snapshot;

CREATE TABLE public.fato_projeto_snapshot (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	current_project_cost_rs numeric(15, 2) NOT NULL,
	total_accumulated_minutes numeric(10, 2) NOT NULL,
	created_at timestamptz NOT NULL,
	projection_end_days int4 NOT NULL,
	project_id int4 NOT NULL,
	snapshot_interval_id int4 NOT NULL,
	CONSTRAINT fato_projeto_snapshot_pkey PRIMARY KEY (id),
	CONSTRAINT fato_projeto_snapshot_project_id_snapshot_inte_4f906d50_uniq UNIQUE (project_id, snapshot_interval_id),
	CONSTRAINT fato_projeto_snapsho_snapshot_interval_id_86e86558_fk_dim_inter FOREIGN KEY (snapshot_interval_id) REFERENCES public.dim_intervalo_temporal(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT fato_projeto_snapshot_project_id_c00524a3_fk_dim_projeto_id FOREIGN KEY (project_id) REFERENCES public.dim_projeto(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX fato_projeto_snapshot_project_id_c00524a3 ON public.fato_projeto_snapshot USING btree (project_id);
CREATE INDEX fato_projeto_snapshot_snapshot_interval_id_86e86558 ON public.fato_projeto_snapshot USING btree (snapshot_interval_id);


-- public.issue definition

-- Drop table

-- DROP TABLE public.issue;

CREATE TABLE public.issue (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(512) NOT NULL,
	details text NOT NULL,
	created_at timestamptz NOT NULL,
	start_date timestamptz NULL,
	end_date timestamptz NULL,
	time_estimate_seconds int4 NULL,
	jira_id int4 NULL,
	id_user int8 NULL,
	project_id int8 NULL,
	status_id int8 NULL,
	type_issue_id int8 NULL,
	CONSTRAINT issue_pkey PRIMARY KEY (id),
	CONSTRAINT issue_id_user_9c1da2ec_fk_accounts_user_id FOREIGN KEY (id_user) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT issue_project_id_fea0fc80_fk_projeto_id FOREIGN KEY (project_id) REFERENCES public.projeto(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT issue_status_id_ace26b12_fk_type_status_id FOREIGN KEY (status_id) REFERENCES public.type_status(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT issue_type_issue_id_c82bc62e_fk_type_issue_id FOREIGN KEY (type_issue_id) REFERENCES public.type_issue(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX issue_id_user_9c1da2ec ON public.issue USING btree (id_user);
CREATE INDEX issue_project_id_fea0fc80 ON public.issue USING btree (project_id);
CREATE INDEX issue_status_id_ace26b12 ON public.issue USING btree (status_id);
CREATE INDEX issue_type_issue_id_c82bc62e ON public.issue USING btree (type_issue_id);


-- public.log_tempo definition

-- Drop table

-- DROP TABLE public.log_tempo;

CREATE TABLE public.log_tempo (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	seconds int4 NOT NULL,
	log_date timestamptz NOT NULL,
	description_log text NOT NULL,
	jira_id int4 NOT NULL,
	id_issue_id int8 NOT NULL,
	id_user_id int8 NULL,
	CONSTRAINT log_tempo_jira_id_key UNIQUE (jira_id),
	CONSTRAINT log_tempo_pkey PRIMARY KEY (id),
	CONSTRAINT log_tempo_id_issue_id_a6d51dc0_fk_issue_id FOREIGN KEY (id_issue_id) REFERENCES public.issue(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT log_tempo_id_user_id_c847c32d_fk_accounts_user_id FOREIGN KEY (id_user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX log_tempo_id_issue_id_a6d51dc0 ON public.log_tempo USING btree (id_issue_id);
CREATE INDEX log_tempo_id_user_id_c847c32d ON public.log_tempo USING btree (id_user_id);


-- public.accounts_user_user_permissions definition

-- Drop table

-- DROP TABLE public.accounts_user_user_permissions;

CREATE TABLE public.accounts_user_user_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);
CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


-- public.auth_group_permissions definition

-- Drop table

-- DROP TABLE public.auth_group_permissions;

CREATE TABLE public.auth_group_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);
