# Generated by Django 4.2.16 on 2025-09-27 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Título ou descrição curta", max_length=512
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Descrição longa ou detalhes adicionais"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data e hora de criação"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de início planejada ou real",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de término planejada ou real",
                        null=True,
                    ),
                ),
                (
                    "time_estimate_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimativa de tempo para conclusão, em segundos",
                        null=True,
                    ),
                ),
                (
                    "jira_id",
                    models.IntegerField(
                        help_text="Identificador único da issue no Jira", null=True
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_user",
                        help_text="O usuário responsável",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "db_table": "issue",
            },
        ),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do tipo de issue (ex: História, Tarefa, Bug)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descrição detalhada do tipo"),
                ),
                (
                    "subtask",
                    models.BooleanField(
                        default=False, help_text="Indica se este tipo é uma subtarefa"
                    ),
                ),
                (
                    "jira_id",
                    models.IntegerField(
                        help_text="Identificador único do tipo de issue no Jira",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Type",
                "verbose_name_plural": "Issue Types",
                "db_table": "type_issue",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="A sigla identificadora", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Nome do projeto", max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Descrição detalhada do projeto"),
                ),
                (
                    "start_date_project",
                    models.DateField(
                        blank=True, help_text="Data de início do projeto", null=True
                    ),
                ),
                (
                    "end_date_project",
                    models.DateField(
                        blank=True, help_text="Data limite de conclusão", null=True
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        help_text="Identificador único do Jira", unique=True
                    ),
                ),
                (
                    "jira_id",
                    models.IntegerField(
                        help_text="Identificador numérico do Jira", unique=True
                    ),
                ),
                (
                    "projectTypeKey",
                    models.CharField(
                        help_text="Tipo do projeto no Jira", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projeto",
            },
        ),
        migrations.CreateModel(
            name="StatusType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="Chave para categoria", max_length=255),
                ),
                ("name", models.TextField(help_text="Nome do status")),
                (
                    "jira_id",
                    models.IntegerField(
                        help_text="Identificador único do Jira", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Type",
                "verbose_name_plural": "Status Types",
                "db_table": "type_status",
            },
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seconds",
                    models.IntegerField(
                        help_text="Quantidade de tempo registrada, em segundos"
                    ),
                ),
                (
                    "log_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que o tempo foi registrado",
                    ),
                ),
                (
                    "description_log",
                    models.TextField(
                        help_text="Descrição ou comentário sobre o trabalho realizado"
                    ),
                ),
                (
                    "jira_id",
                    models.IntegerField(
                        help_text="Identificador único do log de tempo no Jira",
                        unique=True,
                    ),
                ),
                (
                    "id_issue",
                    models.ForeignKey(
                        help_text="Referência para a Issue à qual este log de tempo pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.issue",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que registrou o tempo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Log",
                "verbose_name_plural": "Time Logs",
                "db_table": "log_tempo",
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                help_text="O projeto ao qual a issue pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.ForeignKey(
                help_text="O status atual da issue",
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.statustype",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="type_issue",
            field=models.ForeignKey(
                help_text="O tipo da issue (ex: História, Tarefa, Bug)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.issuetype",
            ),
        ),
    ]
