# Generated by Django 4.2.16 on 2025-09-27 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(blank=True, help_text='O status atual da issue', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.statustype'),
        ),
    ]
