# Generated by Django 4.2.16 on 2025-10-09 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimDev",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="ID Natural do Desenvolvedor",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome_dev", models.CharField(max_length=255)),
                (
                    "id_dev_jiba",
                    models.IntegerField(
                        db_index=True, help_text="ID do Desenvolvedor no jiboia"
                    ),
                ),
                (
                    "id_dev_jira",
                    models.IntegerField(
                        db_index=True, help_text="ID do Desenvolvedor no jira"
                    ),
                ),
                ("valor_hora", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Dimensão Desenvolvedor",
                "db_table": "dim_dev",
            },
        ),
        migrations.CreateModel(
            name="DimIntervaloTemporal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="ID Natural do Intervalo Temporal",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_granularidade",
                    models.CharField(
                        choices=[
                            ("DIA", "Dia"),
                            ("SEMANA", "Semana"),
                            ("MES", "Mês"),
                            ("TRIMESTRE", "Trimestre"),
                            ("SEMESTRE", "Semestre"),
                            ("ANO", "Ano"),
                        ],
                        help_text="Tipo de Período (Dia, Mês, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de inicio em dias, horas e segundos",
                        null=True,
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de fim em dias, horas e segundos",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimensão Intervalo Temporal",
                "db_table": "dim_intervalo_temporal",
            },
        ),
        migrations.CreateModel(
            name="DimProjeto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_projeto_jiba",
                    models.IntegerField(
                        db_index=True, help_text="ID Projeto no jiboia", unique=True
                    ),
                ),
                (
                    "id_projeto_jira",
                    models.IntegerField(
                        db_index=True, help_text="ID Projeto no jira", unique=True
                    ),
                ),
                ("nome_projeto", models.CharField(max_length=255)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
            ],
            options={
                "verbose_name": "Dimensão Projeto",
                "db_table": "dim_projeto",
            },
        ),
        migrations.CreateModel(
            name="DimStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="ID Natural do Status",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_status_jira",
                    models.IntegerField(
                        db_index=True, help_text="ID do Status no jira"
                    ),
                ),
                (
                    "id_status_jiba",
                    models.IntegerField(
                        db_index=True, help_text="ID do Status no jiboia"
                    ),
                ),
                ("nome_status", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Dimensão Status",
                "db_table": "dim_status",
            },
        ),
        migrations.CreateModel(
            name="DimTipoIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="ID Natural do Tipo de Issue",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_tipo_jira",
                    models.IntegerField(help_text="ID do Tipo de Issue no jira"),
                ),
                (
                    "id_tipo_jiba",
                    models.IntegerField(help_text="ID do Tipo de Issue no jiboia"),
                ),
                ("nome_tipo", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Dimensão Tipo de Issue",
                "db_table": "dim_tipo_issue",
            },
        ),
        migrations.CreateModel(
            name="FatoProjetoSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "versao_carga",
                    models.DateTimeField(help_text="Data de criação do snapshot"),
                ),
                (
                    "projecao_termino_dias",
                    models.IntegerField(
                        help_text="Somatória dos dias previsto em todas as issues não finalizadas"
                    ),
                ),
                (
                    "custo_do_projeto_atual_rs",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Somatória das horas dos devs trabalhadas * valor hora respectivo",
                        max_digits=15,
                    ),
                ),
                (
                    "total_horas_acumuladas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total de horas já gastas em desenvolvimento",
                        max_digits=10,
                    ),
                ),
                (
                    "total_issues",
                    models.IntegerField(help_text="Total de issues no projeto"),
                ),
                (
                    "intervalo_snapshot",
                    models.ForeignKey(
                        help_text="Período do Snapshot",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots_projeto",
                        to="core.dimintervalotemporal",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.dimprojeto",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Projeto Snapshot",
                "db_table": "fato_projeto_snapshot",
                "unique_together": {("projeto", "intervalo_snapshot")},
            },
        ),
        migrations.CreateModel(
            name="FatoIssue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "data_criacao",
                    models.DateTimeField(help_text="Data de Criação da Issue"),
                ),
                (
                    "id_issue_jiba",
                    models.IntegerField(
                        db_index=True, help_text="ID Original da Issue no jiboia"
                    ),
                ),
                (
                    "id_issue_jira",
                    models.IntegerField(
                        db_index=True, help_text="ID Original da Issue no jira"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data de criação no modelo dimensional",
                    ),
                ),
                (
                    "dev",
                    models.ForeignKey(
                        help_text="Desenvolvedor que trabalhou na Issue",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.dimdev",
                        verbose_name="Desenvolvedor",
                    ),
                ),
                (
                    "intervalo_trabalho",
                    models.ForeignKey(
                        help_text="Período do Esforço empregado na Issue",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="esforco_issue",
                        to="core.dimintervalotemporal",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        help_text="Projeto ao qual a Issue pertence",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.dimprojeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Status atual da Issue",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.dimstatus",
                        verbose_name="Status da Issue",
                    ),
                ),
                (
                    "tipo_issue",
                    models.ForeignKey(
                        help_text="Tipo da Issue (História, Tarefa, Bug, etc.)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.dimtipoissue",
                        verbose_name="Tipo da Issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato Issue",
                "db_table": "fato_issue",
                "indexes": [
                    models.Index(
                        fields=["projeto", "dev", "data_criacao", "intervalo_trabalho"],
                        name="fato_issue_projeto_872e43_idx",
                    )
                ],
            },
        ),
    ]
