# Generated by Django 4.2.16 on 2025-10-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimDev',
            fields=[
                ('id', models.AutoField(help_text='ID Natural do Desenvolvedor', primary_key=True, serialize=False)),
                ('nome_dev', models.CharField(max_length=255)),
                ('id_dev_jiba', models.IntegerField(db_index=True, help_text='ID do Desenvolvedor no jiboia')),
                ('id_dev_jira', models.IntegerField(db_index=True, help_text='ID do Desenvolvedor no jira')),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da hora do desenvolvedor', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Dimensão Desenvolvedor',
                'db_table': 'dim_dev',
            },
        ),
        migrations.CreateModel(
            name='DimIntervaloTemporal',
            fields=[
                ('id', models.AutoField(help_text='ID Natural do Intervalo Temporal', primary_key=True, serialize=False)),
                ('tipo_granularidade', models.CharField(choices=[('DIA', 'Dia'), ('SEMANA', 'Semana'), ('MES', 'Mês'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('ANO', 'Ano')], help_text='Tipo de Período (Dia, Mês, etc.)', max_length=50)),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data de inicio em dias, horas e segundos', null=True)),
                ('data_fim', models.DateTimeField(blank=True, help_text='Data de fim em dias, horas e segundos', null=True)),
            ],
            options={
                'verbose_name': 'Dimensão Intervalo Temporal',
                'db_table': 'dim_intervalo_temporal',
            },
        ),
        migrations.CreateModel(
            name='DimIssue',
            fields=[
                ('id', models.AutoField(help_text='ID Natural', primary_key=True, serialize=False)),
                ('id_issue_jiba', models.IntegerField(db_index=True, help_text='ID Original da Issue no jiboia')),
                ('id_issue_jira', models.IntegerField(db_index=True, help_text='ID Original da Issue no jira')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da Issue')),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data de início da Issue', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_projeto_jiba', models.IntegerField(db_index=True, help_text='ID Projeto no jiboia', unique=True)),
                ('id_projeto_jira', models.IntegerField(db_index=True, help_text='ID Projeto no jira', unique=True)),
                ('nome_projeto', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(help_text='Data do inicio do projeto')),
            ],
            options={
                'verbose_name': 'Dimensão Projeto',
                'db_table': 'dim_projeto',
            },
        ),
        migrations.CreateModel(
            name='DimStatus',
            fields=[
                ('id', models.AutoField(help_text='ID Natural do Status', primary_key=True, serialize=False)),
                ('id_status_jira', models.IntegerField(db_index=True, help_text='ID do Status no jira')),
                ('id_status_jiba', models.IntegerField(db_index=True, help_text='ID do Status no jiboia')),
                ('nome_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dimensão Status',
                'db_table': 'dim_status',
            },
        ),
        migrations.CreateModel(
            name='DimTipoIssue',
            fields=[
                ('id', models.AutoField(help_text='ID Natural do Tipo de Issue', primary_key=True, serialize=False)),
                ('id_tipo_jira', models.IntegerField(help_text='ID do Tipo de Issue no jira')),
                ('id_tipo_jiba', models.IntegerField(help_text='ID do Tipo de Issue no jiboia')),
                ('nome_tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dimensão Tipo de Issue',
                'db_table': 'dim_tipo_issue',
            },
        ),
        migrations.CreateModel(
            name='FatoEsforco',
            fields=[
                ('id', models.AutoField(help_text='ID Natural do Esforço', primary_key=True, serialize=False)),
                ('custo_acumulado', models.DecimalField(decimal_places=2, help_text='Custo total acumulado', max_digits=15)),
                ('minutos_acumulados', models.IntegerField(help_text='Total de minutos acumulados no período')),
                ('created_at', models.DateTimeField(help_text='Data do Fato Esforço foi criado')),
                ('dev', models.ForeignKey(help_text='Desenvolvedor que realizou o esforço', on_delete=django.db.models.deletion.PROTECT, to='core.dimdev')),
                ('intervalo_trabalho', models.ForeignKey(help_text='Granularidade qual foi realizado e total de minutos (dia, semana, mês, etc.)', on_delete=django.db.models.deletion.PROTECT, to='core.dimintervalotemporal')),
                ('issue', models.ForeignKey(help_text='Issue na qual o esforço foi realizado', on_delete=django.db.models.deletion.PROTECT, to='core.dimissue')),
                ('status', models.ForeignKey(help_text='Status atual da Issue', on_delete=django.db.models.deletion.PROTECT, to='core.dimstatus')),
            ],
        ),
        migrations.AddField(
            model_name='dimissue',
            name='projeto',
            field=models.ForeignKey(help_text='Projeto da Issue', on_delete=django.db.models.deletion.PROTECT, to='core.dimprojeto'),
        ),
        migrations.AddField(
            model_name='dimissue',
            name='tipo_issue',
            field=models.ForeignKey(help_text='Tipo da Issue', on_delete=django.db.models.deletion.PROTECT, to='core.dimtipoissue'),
        ),
        migrations.CreateModel(
            name='FatoProjetoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_projeto_atual_rs', models.DecimalField(decimal_places=2, help_text='Somatória das horas dos devs trabalhadas * valor hora respectivo', max_digits=15)),
                ('total_minutos_acumulados', models.DecimalField(decimal_places=2, help_text='Total de minutos já gastas em desenvolvimento', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do snapshot')),
                ('projecao_termino_dias', models.IntegerField(help_text='Somatória dos dias previsto em todas as issues não finalizadas')),
                ('intervalo_snapshot', models.ForeignKey(help_text='Período do Snapshot', on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_projeto', to='core.dimintervalotemporal')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dimprojeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Fato Projeto Snapshot',
                'db_table': 'fato_projeto_snapshot',
                'unique_together': {('projeto', 'intervalo_snapshot')},
            },
        ),
        migrations.CreateModel(
            name='FatoIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_issue', models.IntegerField(help_text='Total de Issues dos filtros')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação no modelo dimensional')),
                ('intervalo_trabalho', models.ForeignKey(help_text='Período do Esforço empregado na Issue', on_delete=django.db.models.deletion.PROTECT, related_name='esforco_issue', to='core.dimintervalotemporal')),
                ('projeto', models.ForeignKey(help_text='Projeto ao qual a Issue pertence', on_delete=django.db.models.deletion.PROTECT, to='core.dimprojeto', verbose_name='Projeto')),
                ('status', models.ForeignKey(help_text='Status atual da Issue', on_delete=django.db.models.deletion.PROTECT, to='core.dimstatus', verbose_name='Status da Issue')),
                ('tipo_issue', models.ForeignKey(help_text='Tipo da Issue (História, Tarefa, Bug, etc.)', on_delete=django.db.models.deletion.PROTECT, to='core.dimtipoissue', verbose_name='Tipo da Issue')),
            ],
            options={
                'verbose_name': 'Fato Issue',
                'db_table': 'fato_issue',
                'indexes': [models.Index(fields=['projeto', 'intervalo_trabalho'], name='fato_issue_projeto_5ef2ef_idx')],
            },
        ),
    ]
