# Generated by Django 4.2.16 on 2025-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dimdev_dimintervalotemporal_dimprojeto_dimstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimdev',
            name='id_dev_jira',
            field=models.CharField(help_text='ID do Desenvolvedor no jira', max_length=100),
        ),
    ]
