# Generated by Django 4.2.16 on 2025-11-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dimdev_dimintervalotemporal_dimprojeto_dimstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimstatus',
            name='key',
            field=models.CharField(help_text='Key da status', max_length=100, null=True),
        ),
    ]
